### ISSUE TITLE
Service Outage

### ISSUE THREAD

**Issue by dev-head** [BillKeenan/dead-drop-python#13]
Hi there, it appears that the hosted service for this is out: https://dead-drop.me
Looks like a DNS issue, no name servers are showing up for this domain.

**Comment by BillKeenan** [comment]
thanks, seems to have been temporal.

https://www.whatsmydns.net/?utm_source=whatsmydns.com&utm_medium=redirect#NS/dead-drop.me

**Comment by dev-head** [comment]
all fixed, closing out.
