### ISSUE TITLE
non-local mongo DB

### ISSUE THREAD

**Issue by robertorubioguardia** [BillKeenan/dead-drop-python#16]
Hi,

Thanks for this great tool. Is there a way to set this up with a non-local mongo DB? In my particular case, I would like to run it  on Dokku instead of directly into a VM.

Cheers.

**Comment by BillKeenan** [comment]
Glad it's useful.

You can see the mongoclient initialization here, 
https://github.com/BillKeenan/dead-drop-python/blob/master/deadWeb/dead.py#L101

Here's the docs for mongoclient, you can just pop the server address ,port, password in there

https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html
